# Site Settings
title: My Resume
url: 'https://shashankpr.github.io'
baseurl: '/cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Shashank Rao
tagline: Machine Learning Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I believe that AI and Machine Learning are one such exciting field that finds their applications in almost every other domain like Healthcare, Science, Sports, Music and Economics. And this multi-disciplinary aspect of Machine Learning is what makes me feel passionate, motivated and excited.
I am currently a Masters student in Computer Science (Data Science & Technology Track) at TU Delft and during my coursework, I am learning, and have been seeing the way many real-world issues are being tackled by using machine learning. I too have been a part of such venture where I was working on predicting sleep stages of users, using non-intrusive pressure sensitive sensors, and eventually, help users obtain a good quality of sleep. The Deep Neural Network classifier currently achieves an accuracy of around 50% and I am currently researching on improving its predictive capability by incorporating "Unsupervised Feature Learning" using a variant of Convolutional Neural Network. My enthusiasm about machine learning led me to work with LSTM-based networks and learn deep learning libraries like Keras and machine learning libraries like scikit-learn.'

#sidebar links
email: s.p.rao@student.tudelft.nl
phone: +31 6 49184292
website: shashankpr.github.io/blog/ #do not add http://
linkedin: shashankprao
github: shashankpr
twitter: '@shannky16'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
